name: 'Tests Runner'
description: GitHub Action for run tests, Sysdig way'
inputs:
  github_token:
    description: GITHUB_TOKEN secret
    required: true
  artifactory_username:
    description: Artifactory Username
    default: ""
    required: false
  artifactory_password:
    description: Artifactory Password
    default: ""
    required: false
  kind_needed:
    description: "Boolean if a Kubernetes In Docker cluster is needed for tests (default: false)"
    required: false
    default: "true"
  kind_version:
    description: KinD version
    required: false
    default: "v0.11.1"
  kind_config_path:
    description: KinD config path
    required: false
    default: tests/kind-config.yaml
  kind_cluster_name:
    description: KinD cluster name
    required: false
    default: kind
  kind_wait:
    description: KinD wait time for provisioning
    required: false
    default: 60s
  kind_kubectl_version:
    description: kubectl version to use with KinD
    required: false
    default: v1.20.8
  kind_log_level:
    description: KinD verbosity to set
    required: false
    default: "0"
  bats_version:
    description: "BATS version"
    required: false
    default: "1.5.0"
  envsubst_needed:
    description: Indicate if envsubst is needed (only on MacOs)
    required: false
    default: "false"
  taskfile_name:
    description: Name of the taskfile task to be executed
    required: false
    default: "test"
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Setup BATS
      uses: mig4/setup-bats@v1
      with:
        bats-version: ${{ inputs.bats_version }}
    - name: Setup BATS libs
      uses: brokenpip3/setup-bats-libs@0.1.0
    - name: Setup envsubst
      if: ${{ inputs.envsubst_needed == 'true' }}
      shell: bash
      run: sudo apt update; sudo apt install -y gettext-base
    - name: Setup Taskfile
      uses: arduino/setup-task@v1
    - name: Setup Helm
      uses: azure/setup-helm@v2.1
    - name: Setup KinD
      if: ${{ inputs.kind_needed == 'true' }}
      uses: helm/kind-action@v1.2.0
      with:
        version: ${{ inputs.kind_version }}
        config: ${{ inputs.kind_config_path }}
        cluster_name: ${{ inputs.kind_cluster_name }}
        wait: ${{ inputs.kind_wait }}
        kubectl_version: ${{ inputs.kind_kubectl_version }}
        log_level: ${{ inputs.kind_log_level }}
    - name: Lint and tests
      shell: bash
      env:
        GITHUB_REF_NAME: ${{ github.ref }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        ARTIFACTORY_USERNAME: ${{ inputs.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PASSWORD: ${{ inputs.ARTIFACTORY_PASSWORD }}
        TASKFILE_NAME: ${{ inputs.taskfile_name }}
      run: task ${TASKFILE_NAME}
    - name: Clean up
      if: always()
      shell: bash
      run: task test:clean
    - name: Debug failure
      if: failure()
      shell: bash
      run: task test:logs
