name: Sanity Checks
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5.0.0
    - uses: actions/setup-python@v5.6.0
      with:
        python-version: '3.13'
    - uses: pre-commit/action@v3.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
  tagging:
    name: "Tagging (dry-run)"
    needs: pre-commit
    runs-on: ubuntu-latest
    outputs:
      net_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
      - run: echo "Calculated Next Tag is ${{ steps.tag_version.outputs.tags }}"
  test-action-default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: arduino/setup-task@v2
      - name: Test local action
        id: local-action
        uses: ./
  test-action-not-default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: arduino/setup-task@v2
      - name: Test local action
        id: local-action
        uses: ./
        with:
          envsubst_needed: "true"
          taskfile_name: "test:foobar"
