name: "Tag and build"
on:
  push:
    branches: ["main"]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5.0.0
    - uses: actions/setup-python@v6.0.0
      with:
        python-version: '3.13'
    - uses: pre-commit/action@v3.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
  tagging:
    name: "Tagging"
    needs: pre-commit
    runs-on: ubuntu-latest
    outputs:
      next_tag: ${{ steps.tag_version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo Calculated Next Tag is ${{ steps.tag_version.outputs.new_tag }}
